using Olympus.Data;
using Olympus.Rotation.Common;
using Olympus.Rotation.HermesCore.Helpers;

namespace Olympus.Rotation.HermesCore.Context;

/// <summary>
/// Ninja-specific rotation context interface.
/// Extends IMeleeDpsRotationContext with Ninja-specific state.
/// </summary>
public interface IHermesContext : IMeleeDpsRotationContext
{
    #region Ninki Gauge

    /// <summary>
    /// Current Ninki gauge value (0-100).
    /// Spent on Bhavacakra, Hellfrog Medium, Bunshin.
    /// </summary>
    int Ninki { get; }

    /// <summary>
    /// Current Kazematoi stacks (0-5).
    /// Generated by Armor Crush, consumed by Aeolian Edge for bonus damage.
    /// </summary>
    int Kazematoi { get; }

    #endregion

    #region Mudra State

    /// <summary>
    /// Whether a mudra sequence is currently in progress.
    /// </summary>
    bool IsMudraActive { get; }

    /// <summary>
    /// Current mudra count in the active sequence (0-3).
    /// </summary>
    int MudraCount { get; }

    /// <summary>
    /// First mudra in the current sequence.
    /// </summary>
    NINActions.MudraType Mudra1 { get; }

    /// <summary>
    /// Second mudra in the current sequence.
    /// </summary>
    NINActions.MudraType Mudra2 { get; }

    /// <summary>
    /// Third mudra in the current sequence.
    /// </summary>
    NINActions.MudraType Mudra3 { get; }

    /// <summary>
    /// Whether Kassatsu is active (enhances next Ninjutsu).
    /// </summary>
    bool HasKassatsu { get; }

    /// <summary>
    /// Whether Ten Chi Jin mode is active.
    /// </summary>
    bool HasTenChiJin { get; }

    /// <summary>
    /// Remaining stacks of Ten Chi Jin.
    /// </summary>
    int TenChiJinStacks { get; }

    #endregion

    #region Buff State

    /// <summary>
    /// Whether Suiton buff is active (enables Kunai's Bane).
    /// </summary>
    bool HasSuiton { get; }

    /// <summary>
    /// Remaining duration of Suiton in seconds.
    /// </summary>
    float SuitonRemaining { get; }

    /// <summary>
    /// Whether Bunshin is active (shadow clone).
    /// </summary>
    bool HasBunshin { get; }

    /// <summary>
    /// Remaining stacks of Bunshin.
    /// </summary>
    int BunshinStacks { get; }

    /// <summary>
    /// Whether Phantom Kamaitachi is ready.
    /// </summary>
    bool HasPhantomKamaitachiReady { get; }

    /// <summary>
    /// Whether Raiju is ready (Forked/Fleeting).
    /// </summary>
    bool HasRaijuReady { get; }

    /// <summary>
    /// Number of Raiju stacks available.
    /// </summary>
    int RaijuStacks { get; }

    /// <summary>
    /// Whether Meisui is active (enhanced Ninki spenders).
    /// </summary>
    bool HasMeisui { get; }

    /// <summary>
    /// Whether Tenri Jindo is ready (after Kunai's Bane).
    /// </summary>
    bool HasTenriJindoReady { get; }

    #endregion

    #region Debuff State

    /// <summary>
    /// Whether Kunai's Bane debuff is on the target.
    /// </summary>
    bool HasKunaisBaneOnTarget { get; }

    /// <summary>
    /// Remaining duration of Kunai's Bane on target.
    /// </summary>
    float KunaisBaneRemaining { get; }

    /// <summary>
    /// Whether Dokumori debuff is on the target.
    /// </summary>
    bool HasDokumoriOnTarget { get; }

    /// <summary>
    /// Remaining duration of Dokumori on target.
    /// </summary>
    float DokumoriRemaining { get; }

    #endregion

    #region Helpers

    /// <summary>
    /// Status helper for checking buffs/debuffs.
    /// </summary>
    HermesStatusHelper StatusHelper { get; }

    /// <summary>
    /// Party helper for party member queries.
    /// </summary>
    HermesPartyHelper PartyHelper { get; }

    /// <summary>
    /// Mudra helper for sequence tracking and execution.
    /// </summary>
    MudraHelper MudraHelper { get; }

    #endregion

    #region Debug

    /// <summary>
    /// Debug state for this rotation.
    /// </summary>
    HermesDebugState Debug { get; }

    #endregion
}
